export const routes = [
  "/",
  "/pricing/",
  "/faq/",
  "/auth/",
  "/privacy/",
  "/docs/",
  "/docs/getting-started/",
  "/docs/workbench/",
  "/docs/mcp/",
  "/docs/protocol-2026-07-28/",
  "/docs/telemetry/",
  "/docs/api-sdk/",
  "/product/tracing/",
  "/product/logs/",
  "/product/metrics/",
  "/product/mcp-evidence/",
  "/product/ci/",
  "/404.html",
] as const;
